apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openemr-dev
resources:
- ../../base
- secret.yaml
images:
- name: openemr/openemr
  newTag: 8.1.1
patches:
- path: replicas-patch.yaml
