apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openemr-dev
resources:
- ../../base
- secret.yaml
images:
- name: openemr/openemr
  newTag: 8.1.1
patches:
- path: replicas-patch.yaml
# demo test Wed May 20 09:39:10 EAT 2026
# manual ui test Wed May 20 09:57:34 EAT 2026
