apiVersion: apps/v1
kind: Deployment
metadata:
  name: openemr
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: openemr
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
