apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- mysql-deployment.yaml
- mysql-service.yaml
- openemr-deployment.yaml
- openemr-service.yaml
- phpmyadmin-deployment.yaml
- phpmyadmin-service.yaml
