apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: openemr
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: openemr-warehouse
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/tomwakhungu/Hello-openemr.git
          checkout:
          - branch: main
            path: ./repo
      - uses: yaml-update
        config:
          path: repo/manifests/overlays/dev/kustomization.yaml
          updates:
          - key: images.0.newTag
            value: ${{ imageFrom("openemr/openemr").Tag }}
      - uses: git-commit
        config:
          path: ./repo
          message: "chore: promote openemr to dev"
      - uses: git-push
        config:
          path: ./repo
          targetBranch: main
      - uses: argocd-update
        config:
          apps:
          - name: openemr-dev
            namespace: argocd
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: openemr
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: openemr-warehouse
    sources:
      stages:
      - dev
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/tomwakhungu/Hello-openemr.git
          checkout:
          - branch: main
            path: ./repo
      - uses: yaml-update
        config:
          path: repo/manifests/overlays/staging/kustomization.yaml
          updates:
          - key: images.0.newTag
            value: ${{ imageFrom("openemr/openemr").Tag }}
      - uses: git-commit
        config:
          path: ./repo
          message: "chore: promote openemr to staging"
      - uses: git-push
        config:
          path: ./repo
          targetBranch: main
      - uses: argocd-update
        config:
          apps:
          - name: openemr-staging
            namespace: argocd
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: openemr
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: openemr-warehouse
    sources:
      stages:
      - staging
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/tomwakhungu/Hello-openemr.git
          checkout:
          - branch: main
            path: ./repo
      - uses: yaml-update
        config:
          path: repo/manifests/overlays/prod/kustomization.yaml
          updates:
          - key: images.0.newTag
            value: ${{ imageFrom("openemr/openemr").Tag }}
      - uses: git-commit
        config:
          path: ./repo
          message: "chore: promote openemr to prod"
      - uses: git-push
        config:
          path: ./repo
          targetBranch: main
      - uses: argocd-update
        config:
          apps:
          - name: openemr-prod
            namespace: argocd
